### ISSUE TITLE
How can I annotate my own models using this tool?

### ISSUE THREAD

**Issue by mzh19940817** [alvinwan/antsy3d#1]
I want to annotate my own point cloud models using this tool, but it seems that I can't import other models. What should I do? Thanks.

**Comment by alvinwan** [comment]
hello, just convert your data into the format provided in the README. Then, place your file in the javascript src directory, naming the file accordingly. after you label, you should then be able to export the labelled points using the "export" button to the top left.

Update: Here's an example of conversion: https://github.com/alvinwan/antsy2d/blob/master/from_antsy.py
